# Generated by Django 2.0.7 on 2018-08-19 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GuildCreation', '0006_auto_20180813_2300'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildFollowerModel',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('GuildFollowed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuildCreation.GuildModel')),
                ('UserFollowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
