# Generated by Django 2.0.7 on 2018-08-18 02:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GuildCreation', '0006_auto_20180813_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildProfileModel',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('GuildProfileBio', models.TextField(blank=True, max_length=300, null=True)),
                ('GuildProfileJoinDate', models.DateField(default=datetime.date.today)),
                ('GuildProfileImage', models.ImageField(blank=True, default='GuildProfiles/Defaults/Blank.png', null=True, upload_to='GuildProfiles/')),
                ('GuildProfileHeader', models.ImageField(blank=True, default='GuildProfiles/Defaults/BlankWhite.png', null=True, upload_to='GuildProfiles/')),
                ('GuildProfileRelation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GuildCreation.GuildModel')),
            ],
        ),
    ]
