# Generated by Django 2.0.7 on 2018-08-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuildProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildprofilemodel',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
