# Generated by Django 2.0.7 on 2018-08-21 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuildPosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='PostLikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='PostReply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GuildPosts.PostModel'),
        ),
    ]
