# Generated by Django 2.0.7 on 2018-08-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuildPosts', '0002_auto_20180821_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='PostLink',
            field=models.IntegerField(default=493053),
        ),
    ]
