# Generated by Django 2.0.7 on 2018-08-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuildPosts', '0003_postmodel_postlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='PostLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='PostLink',
            field=models.IntegerField(default=4131865439),
        ),
    ]
