# Generated by Django 2.0.7 on 2018-08-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuildPosts', '0004_auto_20180821_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='PostLink',
            field=models.IntegerField(default=5155156550),
        ),
    ]
