# Generated by Django 2.0.7 on 2018-08-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuildPosts', '0007_auto_20180829_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='PostLink',
        ),
    ]
