# Generated by Django 2.0.7 on 2018-08-29 23:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuildPosts', '0010_remove_postmodel_postdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='PostDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='PostLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='PostLink',
            field=models.BigIntegerField(default=9557367945),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='PostReply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GuildPosts.PostModel'),
        ),
    ]
