# Generated by Django 2.0.7 on 2018-08-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuildPosts', '0011_auto_20180829_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='PostLink',
            field=models.BigIntegerField(default=589696148),
        ),
    ]
