# Generated by Django 2.0.7 on 2018-08-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuildPosts', '0012_auto_20180830_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='PostLink',
            field=models.BigIntegerField(default=7975296222),
        ),
    ]
