# Generated by Django 2.0.7 on 2018-08-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuildPosts', '0013_auto_20180830_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='PostLink',
            field=models.BigIntegerField(default=5584200708),
        ),
    ]
