# Generated by Django 2.0.7 on 2018-08-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuildPosts', '0014_auto_20180830_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='PostLink',
            field=models.BigIntegerField(default=814087167),
        ),
    ]
