# Generated by Django 2.0.7 on 2018-08-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuildPosts', '0016_auto_20180830_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='PostLink',
            field=models.BigIntegerField(default=9350519714),
        ),
    ]
