# Generated by Django 2.0.7 on 2018-08-31 13:25

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuildPosts', '0017_auto_20180830_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='SearchVector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='PostLink',
            field=models.BigIntegerField(default=8134019091),
        ),
        migrations.AddIndex(
            model_name='postmodel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['SearchVector'], name='GuildPosts__SearchV_88877c_gin'),
        ),
    ]
