# Generated by Django 2.0.7 on 2018-10-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuildPosts', '0020_auto_20181003_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='PostLink',
            field=models.BigIntegerField(default=3028845758),
        ),
    ]
