# Generated by Django 2.0.7 on 2018-10-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuildPosts', '0021_auto_20181005_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='PostLink',
            field=models.BigIntegerField(default=3937551641),
        ),
    ]
