# Generated by Django 2.0.7 on 2018-10-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuildPosts', '0023_auto_20181006_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='PostLink',
            field=models.BigIntegerField(default=7267025),
        ),
    ]
