# Generated by Django 2.0.7 on 2018-10-07 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GuildPosts', '0024_auto_20181007_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='PostLikes',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='PostLink',
            field=models.BigIntegerField(default=3089169765),
        ),
        migrations.AddField(
            model_name='like',
            name='PostRelation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuildPosts.PostModel'),
        ),
        migrations.AddField(
            model_name='like',
            name='UserRelation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
