# Generated by Django 2.0.7 on 2018-08-13 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuildModel',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('GuildName', models.CharField(max_length=30)),
                ('GuildSize', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('GuildInvite', models.IntegerField()),
            ],
        ),
    ]
