# Generated by Django 2.0.7 on 2018-08-13 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuildCreation', '0002_memberlistmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberlistmodel',
            name='Guild',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GuildCreation.GuildModel'),
        ),
    ]
