# Generated by Django 2.0.7 on 2018-08-13 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GuildCreation', '0003_auto_20180813_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberlistmodel',
            name='Guild',
        ),
        migrations.RemoveField(
            model_name='memberlistmodel',
            name='GuildUser1',
        ),
        migrations.RemoveField(
            model_name='memberlistmodel',
            name='GuildUser2',
        ),
        migrations.RemoveField(
            model_name='memberlistmodel',
            name='GuildUser3',
        ),
        migrations.RemoveField(
            model_name='memberlistmodel',
            name='GuildUser4',
        ),
        migrations.RemoveField(
            model_name='memberlistmodel',
            name='GuildUser5',
        ),
        migrations.DeleteModel(
            name='MemberListModel',
        ),
    ]
