# Generated by Django 2.0.7 on 2018-08-13 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GuildCreation', '0004_auto_20180813_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Guild', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GuildCreation.GuildModel')),
                ('GuildUser1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e', to=settings.AUTH_USER_MODEL)),
                ('GuildUser2', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d', to=settings.AUTH_USER_MODEL)),
                ('GuildUser3', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c', to=settings.AUTH_USER_MODEL)),
                ('GuildUser4', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b', to=settings.AUTH_USER_MODEL)),
                ('GuildUser5', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
