# Generated by Django 2.0.7 on 2018-08-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuildCreation', '0007_auto_20180830_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildmodel',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
