# Generated by Django 2.0.7 on 2018-08-08 00:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('UserProfileBio', models.CharField(max_length=300)),
                ('UserProfileWebsite', models.CharField(max_length=50)),
                ('UserProfileJoinDate', models.DateField(default=datetime.date.today)),
                ('UserProfileRelation', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
