# Generated by Django 2.0.7 on 2018-08-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0003_userprofilemodel_userprofileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='UserProfileHeader',
            field=models.ImageField(blank=True, null=True, upload_to='UserProfiles/'),
        ),
    ]
