# Generated by Django 2.0.7 on 2018-08-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0004_userprofilemodel_userprofileheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='UserProfileBio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='UserProfileWebsite',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
