# Generated by Django 2.0.7 on 2018-08-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0006_auto_20180812_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='UserProfileBio',
            field=models.TextField(default='This profile has not yet been configured, or this field was left blank!', max_length=300),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='UserProfileWebsite',
            field=models.CharField(default='None!', max_length=50),
        ),
    ]
