# Generated by Django 2.0.7 on 2018-08-19 15:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostModel',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('PostBody', models.TextField(max_length=300)),
                ('PostDate', models.DateField(default=datetime.date.today)),
                ('PostUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
