# Generated by Django 2.0.7 on 2018-10-01 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GuildCreation', '0008_auto_20180830_2239'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('PostBody', models.TextField(max_length=300)),
                ('GuildId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuildCreation.GuildModel')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
