# Generated by Django 2.0.7 on 2018-10-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupChat', '0002_auto_20181003_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='MessageBody',
            field=models.CharField(max_length=300),
        ),
    ]
