# Generated by Django 2.0.7 on 2018-10-06 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0009_auto_20180830_2243'),
        ('GroupChat', '0003_auto_20181005_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ProfId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='UserProfiles.UserProfileModel'),
        ),
    ]
